'use client';
import {useState} from 'react';

const destinations=[['Beirut','The vibrant capital — where ancient history meets modern energy','https://monatravel-lb.com/images/beirut.jpg'],['Harissa','Iconic hilltop sanctuary with panoramic bay views','https://monatravel-lb.com/images/harissa.jpg'],['Jeita Grotto','A natural wonder of stunning limestone caves','https://monatravel-lb.com/images/jeita.jpg'],['Baalbek','Magnificent Roman temple ruins — a UNESCO World Heritage Site','https://monatravel-lb.com/images/baalbek.jpg'],['Byblos','One of the oldest continuously inhabited cities in the world','https://monatravel-lb.com/images/byblos.jpg'],['Sidon','Historic coastal city with a legendary sea castle','https://monatravel-lb.com/images/sidon.jpg']];
const leisureServices=[['fa-hotel','Hotel Reservation','Premium accommodations across Lebanon, from boutique hotels in Beirut to charming mountain lodges, all at competitive rates.'],['fa-car','Transport','Comfortable and reliable transportation including airport transfers, private cars and luxury coaches for groups.'],['fa-user-tie','Tour Guide','Certified multilingual guides who bring Lebanon’s history, culture and hidden gems to life.'],['fa-route','Tailored Trips','Customized itineraries designed around your interests, schedule and budget.']];
const mice=[['M','Meetings & Corporate Events','Executive meetings, board meetings, workshops, launches, venue sourcing, DDR packages and on-site coordination.'],['I','Incentive Travel','Bespoke reward journeys combining Lebanese culture, gastronomy, nature, adventure and premium hospitality.'],['C','Conferences & Congresses','Venue sourcing, delegate accommodation, transfers, registration logistics, speakers, AV and gala dinners.'],['E','Exhibitions & Logistics','End-to-end support for exhibitions, trade events, delegations, hospitality desks and group movements.']];
export default function HomePage(){
 const [menu,setMenu]=useState(false);
 const close=()=>setMenu(false);
 return <>
 <div className={'drawer-backdrop '+(menu?'open':'')} onClick={close}/>
 <aside className={'drawer '+(menu?'open':'')}>
  <div className="drawer-head"><div className="brand"><i className="fa-solid fa-plane-departure"/>Mona Travel</div><button className="drawer-close" onClick={close}>×</button></div>
  <div className="drawer-lang"><i className="fa-solid fa-globe"/> &nbsp; EN⌄</div>
  <nav className="drawer-links">{[['Home','home'],['About','about'],['Services','services'],['Destinations','destinations'],['Programs','programs'],['Corporate & MICE','corporate'],['Book Now','book'],['Contact','contact']].map(([t,id])=><a key={id} href={'#'+id} onClick={close}>{t}</a>)}</nav>
  <div className="corp-menu"><small>CORPORATE & MICE</small>
   <a className="corp-item" href="#b2b" onClick={close}><i className="fa-regular fa-building"/><div><b>B2B</b><span>Business Travel & DMC</span></div></a>
   <a className="corp-item" href="#mice" onClick={close}><i className="fa-solid fa-people-group"/><div><b>MICE</b><span>Meetings, Incentives & Events</span></div></a>
   <a className="corp-item" href="#incentives" onClick={close}><i className="fa-solid fa-gift"/><div><b>Incentives</b><span>Motivate. Reward. Inspire.</span></div></a>
   <a className="corp-item" href="#why" onClick={close}><i className="fa-regular fa-star"/><div><b>Why Us</b><span>Our Expertise. Your Advantage.</span></div></a>
   <a className="rfp-btn" href="#rfp" onClick={close}>Submit RFP</a>
  </div>
 </aside>
 <header className="hero" id="home"><nav className="nav"><a href="#home" className="brand"><i className="fa-solid fa-plane-departure"/>Mona Travel</a><div className="desktop-links"><a href="#home">Home</a><a href="#about">About</a><a href="#services">Services</a><a href="#destinations">Destinations</a><a href="#programs">Programs</a><a className="corp" href="#corporate">Corporate & MICE</a><a href="#book">Book Now</a><a href="#contact">Contact</a><span className="lang">◎ EN⌄</span></div><button className="hamb" onClick={()=>setMenu(true)} aria-label="Open menu">☰</button></nav>
 <div className="hero-content"><div className="badge"><i className="fa-regular fa-handshake"/> B2B & MICE SPECIALISTS IN LEBANON</div><h1>Your Premier <em>B2B & MICE</em> Partner in Lebanon</h1><p className="hero-copy">Delivering bespoke corporate events, incentive travel and seamless ground handling through trusted local expertise and strong hospitality partnerships.</p><div className="choice-grid"><article className="choice"><i className="fa-regular fa-building"/><small>BUSINESS TRAVEL & DMC</small><h3>B2B Solutions</h3><p>Corporate travel, delegations, hotel sourcing, executive transport and complete ground handling.</p><a href="#b2b">Explore B2B &nbsp;→</a></article><article className="choice"><i className="fa-solid fa-people-group"/><small>MEETINGS, INCENTIVES & EVENTS</small><h3>MICE Solutions</h3><p>Conferences, exhibitions, incentive trips, gala dinners and end-to-end event management.</p><a href="#mice">Explore MICE &nbsp;→</a></article></div></div></header>
 <section className="section" id="about"><div className="eyebrow">Who We Are</div><h2 className="section-title">About Mona Travel</h2><p className="lead">Mona Travel is a Lebanon-based travel agency officially registered with the Ministry of Tourism. We provide high-quality ground services for international travelers, tour operators and travel agencies, offering authentic, safe and well-organized travel experiences across Lebanon.</p><p className="lead">We specialize in customized travel solutions, transportation services and tourism coordination, while expanding our international B2B network and destination-management capabilities.</p><div className="stats"><div className="stat"><b>Local</b><div>Destination Expertise</div></div><div className="stat"><b>B2B</b><div>Partner Mindset</div></div><div className="stat"><b>360°</b><div>Ground Handling</div></div></div></section>
 <section className="section" id="services" style={{background:'#f0eee8'}}><div className="eyebrow">What We Offer</div><h2 className="section-title">Our Best Services</h2><p className="lead">The complete leisure travel structure remains available alongside our new corporate capabilities.</p><div className="services">{leisureServices.map(([icon,title,text])=><article className="card" key={title}><i className={'fa-solid '+icon}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="section" id="destinations"><div className="eyebrow">Where To Go</div><h2 className="section-title">Tourist Destinations</h2><p className="lead">Discover Lebanon’s most breathtaking locations.</p><div className="destinations">{destinations.map(([name,text,img])=><article className="destination" key={name}><img src={img} alt={name}/><h3>{name}</h3><p>{text}</p></article>)}</div></section>
 <section className="section" id="programs" style={{background:'#f0eee8'}}><div className="eyebrow">Experiences</div><h2 className="section-title">Our Programs</h2><p className="lead">From cultural deep-dives to adrenaline-fueled adventures.</p><div className="program-grid"><article className="program"><h3 className="serif" style={{fontSize:30}}>Cultural & Historical</h3><ul><li>UNESCO Heritage Sites</li><li>Archaeological Tours</li><li>Museums & Cultural Experiences</li><li>Private Guided Tours</li></ul></article><article className="program"><h3 className="serif" style={{fontSize:30}}>Adventure & Nature</h3><ul><li>Cedars Forests</li><li>Hiking & Mountain Experiences</li><li>Paragliding</li><li>Skiing & Eco-Tourism Villages</li></ul></article></div></section>
 <section className="section dark" id="corporate"><div className="eyebrow">Corporate & MICE</div><h2 className="section-title">One Local Partner. Complete Business Solutions.</h2><p className="lead">Mona Travel supports companies, international travel agencies, event organizers, associations and delegations with professional destination management across Lebanon.</p><div className="choice-grid"><article className="choice" id="b2b"><i className="fa-regular fa-building"/><small>B2B TRAVEL & DMC</small><h3>Inbound Corporate Travel</h3><p>Direct hotel sourcing, group accommodation, executive transport, airport meet & assist, business delegations, guides and complete local operations.</p><a href="#rfp">Request B2B Proposal →</a></article><article className="choice"><i className="fa-solid fa-hotel"/><small>BUYING POWER</small><h3>Hotel Partnerships</h3><p>Established direct relationships with hospitality partners help us build competitive group, meeting and accommodation solutions without exposing confidential rates.</p><a href="#rfp">Request Group Rates →</a></article></div></section>
 <section className="section dark" id="mice" style={{paddingTop:20}}><div className="eyebrow">Our MICE Expertise</div><h2 className="section-title">Meetings. Incentives. Conferences. Exhibitions.</h2><div className="mice-grid">{mice.map(([letter,title,text])=><article className="card" key={letter}><div className="gold serif" style={{fontSize:48,fontWeight:700}}>{letter}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="section" id="incentives"><div className="eyebrow">Incentive Travel</div><h2 className="section-title">Reward Your Team With Lebanon</h2><p className="lead">Tailor-made incentive programs can combine Beirut, Byblos, Baalbek, Jeita, Harissa, mountain adventures, winery experiences, private dining and curated Lebanese hospitality.</p><div className="program-grid"><article className="program"><h3 className="serif" style={{fontSize:30}}>Corporate Team Building</h3><p className="lead">Hiking, outdoor challenges, paragliding, culinary experiences, mountain retreats and custom team activities for groups from 10 to 100+ participants.</p></article><article className="program"><h3 className="serif" style={{fontSize:30}}>Bleisure Lebanon</h3><p className="lead">Extend a Beirut business trip or conference stay with one-, two- or multi-day cultural, coastal, culinary and nature experiences.</p></article></div></section>
 <section className="section" id="why" style={{background:'#f0eee8'}}><div className="eyebrow">Why Choose Us?</div><h2 className="section-title">Local Expertise. Strong Partnerships. Seamless Execution.</h2><div className="services"><article className="card"><i className="fa-solid fa-hotel"/><h3>Direct Hotel Buying Power</h3><p>Competitive accommodation and event solutions through established hotel relationships.</p></article><article className="card"><i className="fa-solid fa-location-dot"/><h3>Local Logistics</h3><p>Airport arrival to final departure, coordinated on the ground from one local team.</p></article><article className="card"><i className="fa-solid fa-briefcase"/><h3>B2B Mindset</h3><p>Fast RFP handling, clear quotations, flexibility and transparent corporate invoicing.</p></article><article className="card"><i className="fa-solid fa-diagram-project"/><h3>End-to-End DMC</h3><p>Hotels, venues, transfers, guides, restaurants and activities managed under one partner.</p></article></div></section>
 <section className="section" id="book"><div className="booking"><div><div className="eyebrow">Plan Your Trip</div><h2 className="section-title">Book Your Adventure</h2><p className="lead">For leisure travelers, send your reservation request and our team will craft a personalized itinerary.</p><div style={{marginTop:25}}><b>✓ Secure Booking</b><p className="lead">Your information is safe with us.</p><b>✓ Competitive Rates</b><p className="lead">Tailored options for your travel needs.</p><b>✓ Local Support</b><p className="lead">Professional assistance throughout your trip.</p></div></div><form className="form" onSubmit={e=>{e.preventDefault();alert('Thank you! Your reservation request is ready for the Mona Travel team.')}}><h3 className="serif" style={{fontSize:30,marginTop:0}}>Reservation Request</h3><div className="form-grid"><label className="field">First Name *<input required/></label><label className="field">Last Name *<input required/></label><label className="field">Email *<input type="email" required/></label><label className="field">Phone *<input required/></label><label className="field">Nationality<input/></label><label className="field">Number of Travelers *<input type="number" min="1" required/></label><label className="field">Arrival Date *<input type="date" required/></label><label className="field">Departure Date *<input type="date" required/></label><label className="field full">Trip Type *<select required defaultValue=""><option value="" disabled>Select trip type</option><option>Leisure</option><option>Adventure</option><option>Family</option><option>Honeymoon</option><option>Business Travel</option><option>Corporate Event</option><option>Team Building</option><option>Incentive Travel</option><option>Conference</option></select></label><label className="field full">Special Requests<textarea rows={4}/></label><button className="primary field full">Submit Reservation Request</button></div></form></div></section>
 <section className="section dark" id="rfp"><div className="booking"><div><div className="eyebrow">Corporate Request</div><h2 className="section-title">Submit an RFP</h2><p className="lead">Tell us what your company, agency or organization needs in Lebanon. Our B2B & MICE team can build a tailored ground-handling and event proposal.</p></div><form className="form" style={{color:'#102335'}} onSubmit={e=>{e.preventDefault();alert('Thank you. Your RFP is ready for the Mona Travel B2B & MICE team.')}}><div className="form-grid"><label className="field">Full Name *<input required/></label><label className="field">Business Email *<input type="email" required/></label><label className="field">Company Name *<input required/></label><label className="field">Phone / WhatsApp *<input required/></label><label className="field">Request Type *<select required><option>Corporate Event</option><option>Meeting</option><option>Incentive Travel</option><option>Conference / Congress</option><option>Exhibition</option><option>Team Building</option><option>Business Delegation</option><option>Ground Handling</option></select></label><label className="field">Group Size *<select required><option>1–10</option><option>11–20</option><option>21–50</option><option>51–100</option><option>101–250</option><option>250+</option></select></label><label className="field">Arrival Date<input type="date"/></label><label className="field">Departure Date<input type="date"/></label><label className="field full">Requirements<textarea rows={5}/></label><button className="primary field full">Submit RFP</button></div></form></div></section>
 <section className="section" id="contact"><div className="eyebrow">Reach Out</div><h2 className="section-title">Get in Touch</h2><div className="contact-grid"><div className="contact-card"><b>Phone</b><p>+961 71 472 852</p></div><div className="contact-card"><b>Email</b><p>contact@monatravel-lb.com</p></div><div className="contact-card"><b>Location</b><p>Lebanon</p></div></div></section>
 <footer className="footer"><div className="footer-grid"><div><div className="brand"><i className="fa-solid fa-plane-departure"/>Mona Travel</div><p>Officially registered with the Lebanese Ministry of Tourism. Your trusted partner for authentic Lebanese travel experiences, B2B travel and MICE solutions.</p></div><div><h4>Quick Links</h4><a href="#about">About Us</a><a href="#services">Services</a><a href="#destinations">Destinations</a><a href="#programs">Programs</a></div><div><h4>Corporate</h4><a href="#b2b">B2B</a><a href="#mice">MICE</a><a href="#incentives">Incentives</a><a href="#rfp">Submit RFP</a></div><div><h4>Contact Info</h4><p>+961 71 472 852</p><p>contact@monatravel-lb.com</p><p>Lebanon</p></div></div><div className="copyright">© 2026 Mona Travel. All rights reserved.</div></footer>
 <a className="wa" href="https://wa.me/96171472852" aria-label="WhatsApp"><i className="fa-brands fa-whatsapp"/></a>
 </>;
}
